__title__ = "epic_challenges"
__description__ = "EPIC-Kitchens challenge evaluation code"
__version__ = "0.0.2"
__author__ = "EPIC-Kitchens"
__author_email__ = "uob-epic-kitchens2018@bristol.ac.uk"
__license__ = "MIT"
